on: [push]
name: CI
env:
  MYSQL_ROOT_PASSWORD: drupal
  SIMPLETEST_DB: "mysql://root:drupal@db:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  DRUPAL_MODULE_NAME: "test_module"
  DRUPAL_CORE_VERSION: 9.0.x
jobs:
  test-contrib:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        #php-version: ['7.2', '7.3', '7.4']
        php-version: ['7.4']
    container:
      image: ghcr.io/tuutti/drupal-php-docker:${{ matrix.php-version }}

    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set env variables
        run: echo "$COMPOSER_HOME/.composer/vendor/bin" >> $GITHUB_PATH

      - name: Build project
        run: |
          echo $PATH
          echo $COMPOSER_HOME
          composer global config minimum-stability dev
          composer global config repositories.0 path $GITHUB_WORKSPACE
          composer global require tuutti/drupal-test-runner
          drupal-tr

      - name: Symlink module and update paths
        run: |
          ln -s tests/fixtures/test_module ../drupal/modules
          echo "DRUPAL_MODULE_PATH=tests/fixtures/test_module" >> $DRUPAL_MODULE_PATH

      - name: Run tests
        run: |
          TEST_RUNNER=core drupal-tr run-tests
          TEST_RUNNER=phpunit drupal-tr run-tests
